### ISSUE TITLE
The dog thing

### ISSUE THREAD

**Issue by Person21** [KRHS-GameProgramming-2016/Legend-of-the-Spork#2]
So as I was trying to find which directions that you can go right now, I found that the dog doesn't have the image properly cropped, it still has a white outline around it. I'm also not sure how you are supposed to actually kill the enemies, will there be weapons or something along those lines added in the future?
Keep up the good work
Person21

**Comment by StevenRayno** [comment]
We have the image cropped and white outline is removed. Just that the newest version hasn't been pushed yet. Just make sure to pull again. I am also starting to work on attacking function for the player. Make sure to check the "Projects" tab for more info.
Thanks for the feed back.
StevenRayno
